### ISSUE TITLE
Can't run slurm-web-gen-jwt-key

### ISSUE THREAD

**Issue by alfredhoang** [rackslab/Slurm-web#331]
Environment：
Ubuntu 22.04
Python: 3.10

```
$ pip list
Package            Version
------------------ --------
aiohappyeyeballs   2.3.4
aiohttp            3.10.1
aiosignal          1.3.1
async-timeout      4.0.3
attrs              24.2.0
blinker            1.8.2
certifi            2024.7.4
charset-normalizer 3.3.2
click              8.1.7
ClusterShell       1.9.2
Flask              3.0.3
frozenlist         1.4.1
idna               3.7
itsdangerous       2.2.0
Jinja2             3.1.4
MarkupSafe         2.1.5
multidict          6.0.5
pip                24.2
pyasn1             0.6.0
pyasn1_modules     0.4.0
pycairo            1.26.1
PyGObject          3.48.2
PyJWT              2.9.0
python-ldap        3.4.4
PyYAML             6.0.2
RacksDB            0.4.0
requests           2.32.3
requests-toolbelt  1.0.0
RFL.authentication 1.0.2
RFL.core           1.0.2
RFL.log            1.0.2
RFL.permissions    1.0.2
RFL.settings       1.0.2
RFL.web            1.0.2
setuptools         72.1.0
Slurm-web          3.1.0
urllib3            2.2.2
Werkzeug           3.0.3
wheel              0.44.0
yarl               1.9.4
```

run slurm-web-gen-jwt-key
```
Traceback (most recent call last):
  File "/home/dawn/GitHub/Slurm-web/.venv/bin/slurm-web-gen-jwt-key", line 5, in <module>
    from slurmweb.exec.genjwt import SlurmwebExecGenJWT
  File "/home/dawn/GitHub/Slurm-web/.venv/lib/python3.10/site-packages/slurmweb/exec/genjwt.py", line 13, in <module>
    from ..apps.genjwt import SlurmwebAppGenJWT
  File "/home/dawn/GitHub/Slurm-web/.venv/lib/python3.10/site-packages/slurmweb/apps/genjwt.py", line 15, in <module>
    from rfl.core.utils import shlex_join
ModuleNotFoundError: No module named 'rfl.core.utils'
```
`RFL.core 1.0.3` not found in https://pypi.org/project/RFL.core/#history

This commit doesn't seem to be compatible with Python 3.10 https://github.com/rackslab/Slurm-web/commit/663655b9f3540c141d721b31063a9241dc798976

**Comment by alfredhoang** [comment]
I undo this change and can run.

**Comment by rezib** [comment]
Yes, [RFL](https://github.com/rackslab/RFL) 1.0.3 is not released yet, it will be released in the coming weeks, probably at the end of this month. We ([Rackslab](https://github.com/rackslab)) don't recommend installation of Slurm-web with pip. As [stated in documentation](https://docs.rackslab.io/slurm-web/install/install/sources.html), it should be reserved to setup development environment.

The supported installation method for Slurm-web is to use distribution packages: https://docs.rackslab.io/slurm-web/install/install/distribs/index.html

Then I close this issue as this is not considered as a bug for us.
